import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

import { GeistSans } from 'geist/font/sans';
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "LeapLinks",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${GeistSans.className}`}
        >
          <Toaster />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
